FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends g++ cmake make libmosquitto-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["/bin/sh", "-c", "echo 'Define a producer command in docker-compose.yml' && exit 1"]
